### ISSUE TITLE
二叉树先序遍历函数的传入参数为什么要加“&”？

### ISSUE THREAD

**Issue by yangyuwei5520** [IRVING-L/Algorithm_fromBilibili#1]
二叉树先序遍历函数的传入参数为什么要加“&”？

**Comment by IRVING-L** [comment]
哈哈哈。首先很高兴能够收到你的邮件，在github上留了邮箱，你是第一个给我发邮件的。
关于这个引用&amp;，其实加不加都无所谓。我当时刚刚看完《C++ Primer》，书中的很多范例在传递参数时都是通过引用传递，避免拷贝。深受书里的影响，导致我写这些代码全都加上引用了。
原因就是这么个样子的。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月4日(周四) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [IRVING-L/Algorithm_fromBilibili] 二叉树先序遍历函数的传入参数为什么要加“&amp;”？ (Issue #1)




 
二叉树先序遍历函数的传入参数为什么要加“&amp;”？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IRVING-L** [comment]
哈哈哈。首先很高兴能够收到你反馈。
关于这个引用&，其实加不加都无所谓。
我当时刚刚看完《C++ Primer》，书中的很多范例在传递参数时都是通过引用传递，避免拷贝。深受书里的影响，导致我写这些代码全都加上引用了。
原因就是这么个样子的。。。
